### PR TITLE
Refactor cancel endpoint for RESTX

### PR DESCRIPTION
**Pull request by VickySteeves**

### CODE REVIEW

**Comment by nspektor** [comment]
Travis seems to be saying that the cancel test in TDD is not working... @VickySteeves  do you know whats going on with that?

**Comment by VickySteeves** [comment]
Yes, I figured out why just now. In our `tests/test_service.py` file we had this for the cancel test:

```
# try to cancel it before it's in there
        resp = self.app.post(
            "/promotions/{}/cancel".format(1), content_type="application/json"
        )
        self.assertEqual(resp.status_code, status.HTTP_404_NOT_FOUND)

        # create a new promotion
        test_promotion = self._create_promotions(1)[0]

        # cancel the promotion
        resp = self.app.post(
            "/promotions/{}/cancel".format(test_promotion.id),
            content_type="application/json",
        )
```

That's the wrong URL for cancel. In our README file, we say that the action should come before the ID (like for cancel and apply best promotions). The tests passed when I changed the URLs in the test file to `/promotions/cancel/{}`to reflect that.

**Comment by VickySteeves** [comment]
Just pushed the fix and this should pass all the tests. Apologies!

**Comment by liondon** [comment]
@VickySteeves the `behave` scenario is failing now, I think we also have to change the URL for the `cancel` button on UI?

**Comment by Kristin01** [comment]
Checks failed maybe because there are some problems when merging master branch. I find that `.travis.yml`(seems the old version) and update an existing promotion part in `service/service.py` are different from the master branch and maybe there are other files that are different from the master branch. @VickySteeves, maybe you could check that and make an adjustment.

**Comment by VickySteeves** [comment]
yeah @Kristin01 I just rebased and pushed. The BDD tests are still failing (like ALL of them are) but I think that has to do with the message @liondon just put in slack rather than a problem with how cancel works?

Whoever merges this, for my sake, PLEASE `squash and merge` rather than just merge :sweat:

**Pull request closed without merging**
