### PR TITLE
Add API endpoint that lists all promotions

### PR DESCRIPTION
**Pull request by VickySteeves**
This pull request adds the  endpoint to list all promotions in the database at `promotions/all` and also adds a test that makes sure that the link 200's and that the listed promotions actually exist and match promotions in the DB.

I am not very confident about the test that I wrote, it's probably very inelegant in any event. Would welcome input especially on that but obviously overall as well!

### CODE REVIEW

**Review by liondon — CHANGES_REQUESTED** [review]
Hey @VickySteeves, to follow the RESTful conventions, I think we should just use `/promotions` as the path. 

And we can maybe also add one more log entry before returning the results?

Here's the example I found:
https://github.com/nyu-devops/lab-flask-tdd/blob/master/service/routes.py
```
######################################################################
# LIST ALL PETS
######################################################################
@app.route("/pets", methods=["GET"])
def list_pets():
    """ Returns all of the Pets """
    app.logger.info("Request for pet list")
    pets = []
    category = request.args.get("category")
    name = request.args.get("name")
    if category:
        pets = Pet.find_by_category(category)
    elif name:
        pets = Pet.find_by_name(name)
    else:
        pets = Pet.all()

    results = [pet.serialize() for pet in pets]
    app.logger.info("Returning %d pets", len(results))
    return make_response(jsonify(results), status.HTTP_200_OK)
```

**Comment by liondon** [comment]
And for the test, I think that should be fine? The example didn't even check the id, it only checks the length.

https://github.com/nyu-devops/lab-flask-tdd/blob/master/tests/test_service.py    
```
def test_get_pet_list(self):
        """ Get a list of Pets """
        self._create_pets(5)
        resp = self.app.get("/pets")
        self.assertEqual(resp.status_code, status.HTTP_200_OK)
        data = resp.get_json()
        self.assertEqual(len(data), 5)
```

**Comment by VickySteeves** [comment]
Ok thanks @liondon , I fixed the PR so that it lists things on `/promotions` and adds a second log entry with the number of results being returned.

**Review by VickySteeves — COMMENTED** [review]
thanks for these, I think I addressed them with my latest commit!

**Review by liondon — APPROVED** [review]
Looks great! Let's merge it. :)

**Pull request merged**
