### PR TITLE
Add a single-page UI

### PR DESCRIPTION
**Pull request by VickySteeves**
Ok, I used my favorite Bootswatch theme to make our UI, [Lux](https://bootswatch.com/lux/). We're using the most up-to-date versions of bootstrap and jquery for this as well.

Something to consider was that this "form" (it's not the HTML tag `<form>` because otherwise a lot breaks) doesn't really have a good way to indicate what is necessary for each function we allow. Like for Delete, Cancel, and Retrieve, we really only need the user to provide an `id`. For Create we need everything **except** for the `id`, `duration`, and `active`. In fact, the `active` and  `duration` are really only necessary for the Search function.

BUT our UI right now doesn't have a way to indicate that, and I was not sure we necessarily needed to because we know our API.

Also whoever does the product work (#78 , #77 ) will need to add that into the UI, right now all promotions have an empty `[]` of products associated with them.

### CODE REVIEW

**Comment by sukumarh** [comment]
The UI is loading, with all the fields and buttons. 
I think we can do the filtering of fields based on functions as a part of a separate story.
Do we check the functions (buttons) as a part of this story? I think it makes more sense to update each function with the associated story.
Love the UI though.

image

**Comment by sukumarh** [comment]
> The UI is loading, with all the fields and buttons.
> I think we can do the filtering of fields based on functions as a part of a separate story.
> Do we check the functions (buttons) as a part of this story? I think it makes more sense to update each function with the associated story.
> Love the UI though.
> 
> image

Sorry, just noticed all the functions are working! Let me just test them out and then I'll update it here.

**Comment by sukumarh** [comment]
Tested all the functions, works great! Do you think we should add a ``` List ``` button? Because when we hit the search it always considers ``` is site wide ``` and ``` active ``` as filters.

**Comment by VickySteeves** [comment]
> Tested all the functions, works great! Do you think we should add a `List` button? Because when we hit the search it always considers `is site wide` and `active` as filters.

Yay! I think it's a good idea, should I add that now or should it be a new story?

**Comment by sukumarh** [comment]
> > Tested all the functions, works great! Do you think we should add a `List` button? Because when we hit the search it always considers `is site wide` and `active` as filters.
> 
> Yay! I think it's a good idea, should I add that now or should it be a new story?

We can do it as a new story, most other stories can build upon the current UI.

**Review by sukumarh — APPROVED** [review]

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201117-074514 "deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201117-074514") to [dev](https://console.bluemix.net/apps/42c5c4c9-a7f2-472a-bfb1-add0f77b8a15?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:dev"), including commit a6894a512ead2f7c249ff6d1b91f1a49f38a9a5f

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252 "deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252") to [prod](https://console.bluemix.net/apps/30a9e46b-e89b-4c2e-930e-53e6242584de?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:prod"), including commit a6894a512ead2f7c249ff6d1b91f1a49f38a9a5f

**Pull request merged**
