### PR TITLE
Bdd scnerio cancel

### PR DESCRIPTION
**Pull request by liondon**
I haven't really complete this story cause I didn't figure out how to put `today()` in the scenario. I just hardcoded it for now. Could fix this after tomorrow's class.

### CODE REVIEW

**Comment by sukumarh** [comment]
@liondon Verified the scenario, looks good! For the today thing, maybe using a string pattern can work? I've shared the code below, I ran *behave* along with this code and it works.

Feature:
```bash
   And I should see "$today_date$" in the "end_date" field
```

Update in function:
```code
@then('I should see "{text_string}" in the "{element_name}" field')
def step_impl(context, text_string, element_name):
    element_id = ID_PREFIX + element_name.lower()
    
    from datetime import date
    if text_string == "$today_date$":
        text = date.today().strftime("%Y-%m-%d")
    else:
        text = text_string

    found = WebDriverWait(context.driver, WAIT_SECONDS).until(
        expected_conditions.text_to_be_present_in_element_value(
            (By.ID, element_id),
            text
        )
    )
    expect(found).to_be(True)
```

**Review by sukumarh — APPROVED** [review]
Ran both the TDDs and BDDs, good to merge!

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601 "deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601") to [dev](https://console.bluemix.net/apps/42c5c4c9-a7f2-472a-bfb1-add0f77b8a15?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:dev"), including commit 6fd0b63e6ba73d7d1aab995439c1d12a7628deac

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252 "deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252") to [prod](https://console.bluemix.net/apps/30a9e46b-e89b-4c2e-930e-53e6242584de?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:prod"), including commit 6fd0b63e6ba73d7d1aab995439c1d12a7628deac

**Pull request merged**
