### PR TITLE
Add honcho

### PR DESCRIPTION
**Pull request by Kristin01**

### CODE REVIEW

**Comment by nspektor** [comment]
This is to fulfil this requirement on the hw right? 
"Add honcho to your requirements.txt file and make sure the the
command: honcho start works with your Procfile."
I tried pulling your branch, pip installing requirements and running honcho start and all works fine!

Quick question: why are there also so many other changes to requirements.txt? are they requirements for honcho to work?

**Comment by Kristin01** [comment]
Yeah, it's to fulfill the requirement on the hw.
I just “borrowed” the commands from the requirements.txt of `lab-bluemix-cf` repo.  They are not needed for honcho, maybe for other features. So I think they don't need to be kept in this story. I'll make a change. Thanks for pointing that out.

**Review by nspektor — APPROVED** [review]
awesome, thanks for changing

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201117-074514 "deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201117-074514") to [dev](https://console.bluemix.net/apps/42c5c4c9-a7f2-472a-bfb1-add0f77b8a15?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:dev"), including commit 3679dce09a990b89cf59b5a205457a5fbb1c8c17

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252 "deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252") to [prod](https://console.bluemix.net/apps/30a9e46b-e89b-4c2e-930e-53e6242584de?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:prod"), including commit 3679dce09a990b89cf59b5a205457a5fbb1c8c17

**Pull request merged**
