### PR TITLE
BDD scenario query

### PR DESCRIPTION
**Pull request by sukumarh**
This PR has the following changes:
1. Fixed the connection to the service.
2. Added additional sample data to create more query scenarios.
2. Added a scenario for the Query endpoint.

Should I add more query scenarios before closing this story or can we do that as a part of another story?

### CODE REVIEW

**Review by nspektor — APPROVED** [review]
This looks good, tested it locally, I am not sure whether we should add more query tests. Maybe we can ask the professor how extensive the behave tests should be, should they test every possibility like the TDD tests? if so then i would say that there should be some more tests in this story, if not then this seems good

**Comment by nspektor** [comment]
Given slack convo with professor, I am going to merge this in

**Comment by nspektor** [comment]
May have jumped the gun a bit on merging this, there seem to be some problems with querying on site-wide and active - we should file a bug fix ticket for investigating, fixing and testing this issue

**Comment by sukumarh** [comment]
> May have jumped the gun a bit on merging this, there seem to be some problems with querying on site-wide and active - we should file a bug fix ticket for investigating, fixing and testing this issue

@nspektor Thanks for pointing that out, I'm checking the pull request right now. I'll comment as soon as I go through the changes. And thanks for confirming with the professor about the query scenarios, I think it makes sense to have a single case that covers a good bandwidth of filters.

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601 "deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601") to [dev](https://console.bluemix.net/apps/42c5c4c9-a7f2-472a-bfb1-add0f77b8a15?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:dev"), including commit 900eb90c7b6111c777cdda042f6be9a5799b9369

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252 "deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252") to [prod](https://console.bluemix.net/apps/30a9e46b-e89b-4c2e-930e-53e6242584de?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:prod"), including commit 900eb90c7b6111c777cdda042f6be9a5799b9369

**Pull request merged**
