### PR TITLE
BDD scenario delete

### PR DESCRIPTION
**Pull request by nspektor**
I included some commented out Behave lines in here because they should work, but do not because of the bug with querying on site-wide and on active. I could just delete them and mention them in the bug fix ticket, but wanted to include here for context on our slack convo @VickySteeves @sukumarh

### CODE REVIEW

**Comment by sukumarh** [comment]
The tests passed and I checked the functionality manually as well. It seems to be working as expected. But I noticed a ``` 404 ``` response on the ``` DELETE ``` request on the flask terminal. The ``` 404 ``` on the ``` GET ``` request makes sense cause that is the validation of the deleted record not being present.

The screenshot below is after I run the tests.

image

**Comment by nspektor** [comment]
The bug you pointed out should be fixed now @sukumarh let me know if thats not the case

**Review by sukumarh — APPROVED** [review]
Great! The 404 is gone now. Verified it just now, going to merge.

**Comment by sukumarh** [comment]
> Great! The 404 is gone now. Verified it just now, going to merge.

Before that, could you merge the conflicts with master? @nspektor

**Comment by Kristin01** [comment]
All passed, I'll merge it.

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601 "deploy-ibm-yp-us-south-2020-nyu-devops-dev-20201122-075601") to [dev](https://console.bluemix.net/apps/42c5c4c9-a7f2-472a-bfb1-add0f77b8a15?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:dev"), including commit 78b7ffa71c5009e1aab289ab07351b96343072e4

**Comment by liondon** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/82ed68f3-a995-419e-80a4-f9191b98d0a4?env_id=ibm:yp:us-south "nyu-devops-promo-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/a90cf2f8-b961-4e4c-98ff-49891084d12b "nyu-devops-promo-pipeline") deployed [promotions](https://github.com/2020-nyu-devops/promotions/releases/tag/deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252 "deploy-ibm-yp-us-south-2020-nyu-devops-prod-20201122-080252") to [prod](https://console.bluemix.net/apps/30a9e46b-e89b-4c2e-930e-53e6242584de?env_id=ibm:yp:us-south "ibm:yp:us-south:2020-nyu-devops:prod"), including commit 78b7ffa71c5009e1aab289ab07351b96343072e4

**Pull request merged**
